# Generated by Django 4.1.6 on 2023-02-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0003_remove_order_date_tax_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
