# Generated by Django 4.1.6 on 2023-02-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0006_item_discount_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_discounts', to='transition.discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_discounts', to='transition.item'),
        ),
    ]
