# Generated by Django 4.1.6 on 2023-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0007_item_discount_alter_discount_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
    ]
