# Generated by Django 4.1.6 on 2023-02-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0008_order_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_item',
        ),
        migrations.AddField(
            model_name='item',
            name='tax_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_taxes', to='transition.tax'),
        ),
    ]
