# Generated by Django 4.1.6 on 2023-02-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0009_remove_item_discount_item_item_tax_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='discount_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_discounts_set', to='transition.discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='transition.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_taxes_set', to='transition.tax'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='transition.item'),
        ),
    ]
