# Generated by Django 4.1.6 on 2023-02-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0010_remove_discount_order_remove_item_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='item',
        ),
    ]
