# Generated by Django 4.1.6 on 2023-02-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0011_remove_discount_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='item',
        ),
    ]
