# Generated by Django 4.1.6 on 2023-02-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0015_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
