# Generated by Django 4.1.6 on 2023-02-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0017_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
